/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gradesmart.GradeSmart;

import static com.gradesmart.GradeSmart.gradeSmart.db.DB_URL;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.persistence.EntityManagerFactory;
//import javax.persistence.Persistence;

/**
 *
 * @author Harpreet
 */
public class AddClass extends javax.swing.JFrame {

    /**
     * Creates new form AddClass
     */
    public AddClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        GradeSmartPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("GradeSmartPU").createEntityManager();
        coursesQuery = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT c FROM Courses c");
        coursesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coursesQuery.getResultList();
        userCoursesQuery = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT u FROM UserCourses u");
        userCoursesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : userCoursesQuery.getResultList();
        coursesQuery1 = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT c FROM Courses c");
        coursesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coursesQuery1.getResultList();
        coursesQuery2 = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT c FROM Courses c");
        coursesList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coursesQuery2.getResultList();
        coursesQuery3 = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT c FROM Courses c");
        coursesList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coursesQuery3.getResultList();
        coursesQuery4 = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT c FROM Courses c");
        coursesList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coursesQuery4.getResultList();
        userCoursesQuery1 = java.beans.Beans.isDesignTime() ? null : GradeSmartPUEntityManager.createQuery("SELECT u FROM UserCourses u");
        userCoursesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : userCoursesQuery1.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        selectButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        courseTable.setColumnSelectionAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, coursesList4, courseTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${crn}"));
        columnBinding.setColumnName("Crn");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${coursename}"));
        columnBinding.setColumnName("Coursename");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${instructor}"));
        columnBinding.setColumnName("Instructor");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(courseTable);
        courseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        selectButton.setText("SELECT");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, userCoursesList1, jTable1);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${crn}"));
        columnBinding.setColumnName("Crn");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${coursename}"));
        columnBinding.setColumnName("Coursename");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${instructor}"));
        columnBinding.setColumnName("Instructor");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(selectButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(selectButton)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


//    
    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
//        // optional: ask user if they wish to add the following courses. update CID. 
//        // optional: textfields for user input https://www.youtube.com/watch?v=uJUXyhya3YM
//        
           String DB_URL = "jdbc:derby://localhost:1527/gradesmartdb"; 
           String DB_USER = "wasfi";
           String DB_PASSWORD = "wasfi";
        
       // here we open the database for all the Courses for user selection which
       // will be populated into a new table UserCourses.
        Courses c1 = new Courses(); 
        UserCourses u1 = new UserCourses();


        // create query and send to user_courses database.
        try {
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement updateUserCourse = conn.createStatement();
            ResultSet rs = null;
             
            //optional: select multiple rows
              int selectedRow = courseTable.getSelectedRow();

                 u1.setCrn(Integer.parseInt(courseTable.getValueAt(selectedRow, 0).toString()));
                 u1.setCoursename(courseTable.getValueAt(selectedRow,1).toString());
                 u1.setInstructor(courseTable.getValueAt(selectedRow,2).toString());
                 
            

                 System.out.print(u1.getCrn() + "\t" + u1.getCoursename() + "\t" + u1.getInstructor() + "\n");
                 String query = "INSERT INTO USER_COURSES (CRN, COURSENAME, INSTRUCTOR) VALUES(" + u1.getCrn() +", '" + 
                            u1.getCoursename() + "', '" + u1.getInstructor() + "')";
                 
                 updateUserCourse.executeUpdate(query);
                 
                 
                System.out.println(query);


                            
           
            
        } catch (SQLException ex) {
            System.err.println("SQL connection failed." );
            ex.printStackTrace();
            
            Logger.getLogger(gradeSmart.class.getName()).log(Level.SEVERE, null, ex);
            
        }
         
        
        
//        this.setVisible(false); // hide jframe once classes are added
        
    }//GEN-LAST:event_selectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager GradeSmartPUEntityManager;
    private javax.swing.JTable courseTable;
    private java.util.List<com.gradesmart.GradeSmart.Courses> coursesList;
    private java.util.List<com.gradesmart.GradeSmart.Courses> coursesList1;
    private java.util.List<com.gradesmart.GradeSmart.Courses> coursesList2;
    private java.util.List<com.gradesmart.GradeSmart.Courses> coursesList3;
    private java.util.List<com.gradesmart.GradeSmart.Courses> coursesList4;
    private javax.persistence.Query coursesQuery;
    private javax.persistence.Query coursesQuery1;
    private javax.persistence.Query coursesQuery2;
    private javax.persistence.Query coursesQuery3;
    private javax.persistence.Query coursesQuery4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton selectButton;
    private java.util.List<com.gradesmart.GradeSmart.UserCourses> userCoursesList;
    private java.util.List<com.gradesmart.GradeSmart.UserCourses> userCoursesList1;
    private javax.persistence.Query userCoursesQuery;
    private javax.persistence.Query userCoursesQuery1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
