/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gradesmartt.w;

/**
 *
 * @author Akshar
 */
public class ForgotUsername extends javax.swing.JFrame {
    
    public String email = "akshar1095@gmail.com";
    public String username = "apatel203";

    /**
     * Creates new form ForgotUsername
     */
    public ForgotUsername() {
        initComponents();
        emailNotFoundLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotUserPanel = new javax.swing.JPanel();
        forgotUserLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        emailNotFoundLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        userFoundPanel = new javax.swing.JPanel();
        userFoundLabel = new javax.swing.JLabel();
        foundUserLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        forgotUserLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        forgotUserLabel.setForeground(new java.awt.Color(51, 55, 69));
        forgotUserLabel.setText("Forgot Username");

        emailLabel.setText("Email: ");
        emailLabel.setPreferredSize(new java.awt.Dimension(42, 15));

        emailInput.setPreferredSize(new java.awt.Dimension(10, 25));
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        findButton.setText("Find");
        findButton.setPreferredSize(new java.awt.Dimension(100, 30));
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        emailNotFoundLabel.setForeground(new java.awt.Color(255, 0, 0));
        emailNotFoundLabel.setText("The Email you have entered does not exist in our system!");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotUserPanelLayout = new javax.swing.GroupLayout(forgotUserPanel);
        forgotUserPanel.setLayout(forgotUserPanelLayout);
        forgotUserPanelLayout.setHorizontalGroup(
            forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotUserPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(forgotUserPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(forgotUserLabel)))
                    .addComponent(emailNotFoundLabel))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(forgotUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forgotUserPanelLayout.setVerticalGroup(
            forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(forgotUserLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(forgotUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailNotFoundLabel)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(forgotUserPanel, "card2");

        userFoundLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        userFoundLabel.setForeground(new java.awt.Color(51, 55, 69));
        userFoundLabel.setText("User Found");

        foundUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        foundUserLabel.setText("username");

        okButton.setText("OK");
        okButton.setPreferredSize(new java.awt.Dimension(100, 30));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userFoundPanelLayout = new javax.swing.GroupLayout(userFoundPanel);
        userFoundPanel.setLayout(userFoundPanelLayout);
        userFoundPanelLayout.setHorizontalGroup(
            userFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFoundPanelLayout.createSequentialGroup()
                .addGroup(userFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userFoundPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userFoundPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(foundUserLabel))
                    .addGroup(userFoundPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(userFoundLabel)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        userFoundPanelLayout.setVerticalGroup(
            userFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFoundPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(userFoundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(foundUserLabel)
                .addGap(18, 18, 18)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(userFoundPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
        if(emailInput.getText().equals("")){
            emailNotFoundLabel.setText("Enter an Email!");
            emailNotFoundLabel.setVisible(true);
        }
        else {
            if(UserList.userRecover.containsKey(emailInput.getText())){
                username = UserList.userRecover.get(emailInput.getText());
                forgotUserPanel.setVisible(false);
                userFoundPanel.setVisible(true);
                emailNotFoundLabel.setVisible(false);
                foundUserLabel.setText(username);
            }
            else{
                emailNotFoundLabel.setText("Email does not exist in system!");
                emailNotFoundLabel.setVisible(true);
            }
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_okButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotUsername().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailNotFoundLabel;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel forgotUserLabel;
    private javax.swing.JPanel forgotUserPanel;
    private javax.swing.JLabel foundUserLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel userFoundLabel;
    private javax.swing.JPanel userFoundPanel;
    // End of variables declaration//GEN-END:variables
}
