/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gradesmartt.w;

/**
 *
 * @author Akshar
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    public String username = "apatel203";
    public String favHistPerson;
    public String favMovie;
    public String favTeam;
   
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        errorMessageLabelOne.setVisible(false);
        errorMessageLabelTwo.setVisible(false);
        errorMessageLabelThree.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotPassPanel = new javax.swing.JPanel();
        titleLabelOne = new javax.swing.JLabel();
        userLabelOne = new javax.swing.JLabel();
        userInputOne = new javax.swing.JTextField();
        forgotUserButton = new javax.swing.JButton();
        continueButtonOne = new javax.swing.JButton();
        errorMessageLabelOne = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        recoveryQuestionPanel = new javax.swing.JPanel();
        titleLabelTwo = new javax.swing.JLabel();
        favHistPersonLabel = new javax.swing.JLabel();
        favMovieLabel = new javax.swing.JLabel();
        favTeamLabel = new javax.swing.JLabel();
        favHistPersonInput = new javax.swing.JTextField();
        favMovieInput = new javax.swing.JTextField();
        favTeamInput = new javax.swing.JTextField();
        continueButtonTwo = new javax.swing.JButton();
        errorMessageLabelTwo = new javax.swing.JLabel();
        resetPassPanel = new javax.swing.JPanel();
        titleLabelThree = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        retypePassLabel = new javax.swing.JLabel();
        newPassInput = new javax.swing.JTextField();
        retypePassInput = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        errorMessageLabelThree = new javax.swing.JLabel();
        passResetConfirmPanel = new javax.swing.JPanel();
        titleLabelFour = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        titleLabelOne.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        titleLabelOne.setForeground(new java.awt.Color(51, 55, 69));
        titleLabelOne.setText("Forgot Password");

        userLabelOne.setText("Username: ");
        userLabelOne.setPreferredSize(new java.awt.Dimension(70, 15));

        userInputOne.setPreferredSize(new java.awt.Dimension(10, 25));

        forgotUserButton.setText("Forgot Username");
        forgotUserButton.setPreferredSize(new java.awt.Dimension(150, 30));
        forgotUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotUserButtonActionPerformed(evt);
            }
        });

        continueButtonOne.setText("Continue");
        continueButtonOne.setPreferredSize(new java.awt.Dimension(100, 30));
        continueButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonOneActionPerformed(evt);
            }
        });

        errorMessageLabelOne.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabelOne.setText("Error Message!");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotPassPanelLayout = new javax.swing.GroupLayout(forgotPassPanel);
        forgotPassPanel.setLayout(forgotPassPanelLayout);
        forgotPassPanelLayout.setHorizontalGroup(
            forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPassPanelLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(forgotPassPanelLayout.createSequentialGroup()
                        .addComponent(forgotUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotPassPanelLayout.createSequentialGroup()
                        .addComponent(userLabelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userInputOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titleLabelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMessageLabelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(forgotPassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forgotPassPanelLayout.setVerticalGroup(
            forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabelOne)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userInputOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forgotUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(continueButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorMessageLabelOne)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(forgotPassPanel, "card7");

        recoveryQuestionPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        titleLabelTwo.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        titleLabelTwo.setForeground(new java.awt.Color(51, 55, 69));
        titleLabelTwo.setText("Recovery Questions");

        favHistPersonLabel.setText("Favorite Historical Figure: ");
        favHistPersonLabel.setPreferredSize(new java.awt.Dimension(166, 15));

        favMovieLabel.setText("Favorite Movie: ");
        favMovieLabel.setPreferredSize(new java.awt.Dimension(100, 15));

        favTeamLabel.setText("Favorite Sports Team: ");
        favTeamLabel.setPreferredSize(new java.awt.Dimension(140, 15));

        continueButtonTwo.setText("Continue");
        continueButtonTwo.setPreferredSize(new java.awt.Dimension(100, 30));
        continueButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonTwoActionPerformed(evt);
            }
        });

        errorMessageLabelTwo.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabelTwo.setText("Error Message!");

        javax.swing.GroupLayout recoveryQuestionPanelLayout = new javax.swing.GroupLayout(recoveryQuestionPanel);
        recoveryQuestionPanel.setLayout(recoveryQuestionPanelLayout);
        recoveryQuestionPanelLayout.setHorizontalGroup(
            recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recoveryQuestionPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabelTwo)
                    .addGroup(recoveryQuestionPanelLayout.createSequentialGroup()
                        .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(favHistPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(favMovieLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(favTeamLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(favHistPersonInput)
                            .addComponent(favMovieInput)
                            .addComponent(favTeamInput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recoveryQuestionPanelLayout.createSequentialGroup()
                        .addComponent(errorMessageLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(continueButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        recoveryQuestionPanelLayout.setVerticalGroup(
            recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recoveryQuestionPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(titleLabelTwo)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favHistPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favHistPersonInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favMovieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favMovieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favTeamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(recoveryQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMessageLabelTwo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(recoveryQuestionPanel, "card3");

        resetPassPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        titleLabelThree.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        titleLabelThree.setForeground(new java.awt.Color(51, 55, 69));
        titleLabelThree.setText("Reset Password");

        newPassLabel.setText("New Password: ");
        newPassLabel.setPreferredSize(new java.awt.Dimension(98, 15));

        retypePassLabel.setText("Retype New Password: ");
        retypePassLabel.setPreferredSize(new java.awt.Dimension(144, 15));

        newPassInput.setPreferredSize(new java.awt.Dimension(80, 25));
        newPassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassInputActionPerformed(evt);
            }
        });

        retypePassInput.setPreferredSize(new java.awt.Dimension(80, 25));

        confirmButton.setText("Confirm");
        confirmButton.setPreferredSize(new java.awt.Dimension(100, 30));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        errorMessageLabelThree.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabelThree.setText("Error Message!");

        javax.swing.GroupLayout resetPassPanelLayout = new javax.swing.GroupLayout(resetPassPanel);
        resetPassPanel.setLayout(resetPassPanelLayout);
        resetPassPanelLayout.setHorizontalGroup(
            resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPassPanelLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titleLabelThree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resetPassPanelLayout.createSequentialGroup()
                        .addGroup(resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retypePassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPassInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retypePassInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMessageLabelThree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        resetPassPanelLayout.setVerticalGroup(
            resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPassPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(titleLabelThree)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(resetPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retypePassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessageLabelThree)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(resetPassPanel, "card4");

        titleLabelFour.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        titleLabelFour.setForeground(new java.awt.Color(51, 55, 69));
        titleLabelFour.setText("Password Reset Confirmed!");

        okButton.setText("OK");
        okButton.setPreferredSize(new java.awt.Dimension(100, 30));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passResetConfirmPanelLayout = new javax.swing.GroupLayout(passResetConfirmPanel);
        passResetConfirmPanel.setLayout(passResetConfirmPanelLayout);
        passResetConfirmPanelLayout.setHorizontalGroup(
            passResetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passResetConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(titleLabelFour)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(passResetConfirmPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passResetConfirmPanelLayout.setVerticalGroup(
            passResetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passResetConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(titleLabelFour)
                .addGap(18, 18, 18)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(passResetConfirmPanel, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotUserButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ForgotUsername tmp = new ForgotUsername();
        tmp.setVisible(true);
    }//GEN-LAST:event_forgotUserButtonActionPerformed

    private void continueButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonOneActionPerformed
        // TODO add your handling code here:
        if(userInputOne.getText().equals("")){
            errorMessageLabelOne.setText("Enter an Username!");
            errorMessageLabelOne.setVisible(true);
        }
        else{
            if(UserList.users.containsKey(userInputOne.getText()) == false){
            errorMessageLabelOne.setText("Sorry user does not exist in the system!");
            errorMessageLabelOne.setVisible(true);
            }
            else{
            favHistPerson = UserList.users.get(userInputOne.getText()).getAnswerOne();
            favMovie = UserList.users.get(userInputOne.getText()).getAnswerTwo();
            favTeam = UserList.users.get(userInputOne.getText()).getAnswerThree();
            errorMessageLabelOne.setVisible(false);
            forgotPassPanel.setVisible(false);
            recoveryQuestionPanel.setVisible(true);
            }  
        }
    }//GEN-LAST:event_continueButtonOneActionPerformed

    private void continueButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonTwoActionPerformed
        // TODO add your handling code here:
        
        if(favHistPersonInput.getText().equals(favHistPerson) == false){
            errorMessageLabelTwo.setText("Sorry your answer or answers do not match!");
            errorMessageLabelTwo.setVisible(true);
        }
        else if(favMovieInput.getText().equals(favMovie) == false){
            errorMessageLabelTwo.setText("Sorry your answer or answers do not match!");
            errorMessageLabelTwo.setVisible(true);
        }
        else if(favTeamInput.getText().equals(favTeam) == false){
            errorMessageLabelTwo.setText("Sorry your answer or answers do not match!");
            errorMessageLabelTwo.setVisible(true);
        }
        else{
            errorMessageLabelTwo.setVisible(false);
            recoveryQuestionPanel.setVisible(false);
            resetPassPanel.setVisible(true);
        }
    }//GEN-LAST:event_continueButtonTwoActionPerformed

    private void newPassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassInputActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(newPassInput.getText().equals("")){
                errorMessageLabelThree.setText("You need to put in a new password!");
                errorMessageLabelThree.setVisible(true);            
        }
        else{
            if(newPassInput.getText().equals(retypePassInput.getText()) == false){
                errorMessageLabelThree.setText("Sorry your passwords do not match!");
                errorMessageLabelThree.setVisible(true);
            }
            else{
                User tmpUser = UserList.users.get(userInputOne.getText());
                tmpUser.setPassword(newPassInput.getText());
                
                UserList.users.remove(userInputOne.getText());
                UserList.users.put(tmpUser.getUsername(),tmpUser);
                
                errorMessageLabelThree.setVisible(false);
                resetPassPanel.setVisible(false);
                passResetConfirmPanel.setVisible(true);
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_okButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton continueButtonOne;
    private javax.swing.JButton continueButtonTwo;
    private javax.swing.JLabel errorMessageLabelOne;
    private javax.swing.JLabel errorMessageLabelThree;
    private javax.swing.JLabel errorMessageLabelTwo;
    private javax.swing.JTextField favHistPersonInput;
    private javax.swing.JLabel favHistPersonLabel;
    private javax.swing.JTextField favMovieInput;
    private javax.swing.JLabel favMovieLabel;
    private javax.swing.JTextField favTeamInput;
    private javax.swing.JLabel favTeamLabel;
    private javax.swing.JPanel forgotPassPanel;
    private javax.swing.JButton forgotUserButton;
    private javax.swing.JTextField newPassInput;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel passResetConfirmPanel;
    private javax.swing.JPanel recoveryQuestionPanel;
    private javax.swing.JPanel resetPassPanel;
    private javax.swing.JTextField retypePassInput;
    private javax.swing.JLabel retypePassLabel;
    private javax.swing.JLabel titleLabelFour;
    private javax.swing.JLabel titleLabelOne;
    private javax.swing.JLabel titleLabelThree;
    private javax.swing.JLabel titleLabelTwo;
    private javax.swing.JTextField userInputOne;
    private javax.swing.JLabel userLabelOne;
    // End of variables declaration//GEN-END:variables
}
