/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gradesmartt.w;

/**
 *
 * @author Akshar
 */
public class NewUser extends javax.swing.JFrame {
 
    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        errorMessageLabel.setVisible(false);
        errorMessageLabelTwo.setVisible(false);
        UserList.getInstance();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserDetailsPanel = new javax.swing.JPanel();
        newUserDetailsLabel = new javax.swing.JLabel();
        userLabelOne = new javax.swing.JLabel();
        passLabelOne = new javax.swing.JLabel();
        retypePassLabel = new javax.swing.JLabel();
        emailLabelOne = new javax.swing.JLabel();
        lastLabelOne = new javax.swing.JLabel();
        firstLabelOne = new javax.swing.JLabel();
        dobLabelOne = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        passInput = new javax.swing.JTextField();
        retypePassInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        firstInput = new javax.swing.JTextField();
        lastInput = new javax.swing.JTextField();
        dobInput = new javax.swing.JTextField();
        continueButtonOne = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        newUserQuestionsPanel = new javax.swing.JPanel();
        newUserQuestionsLabel = new javax.swing.JLabel();
        favHistLabelOne = new javax.swing.JLabel();
        favMovieLabelOne = new javax.swing.JLabel();
        favTeamLabelOne = new javax.swing.JLabel();
        favHistInput = new javax.swing.JTextField();
        favMovieInput = new javax.swing.JTextField();
        favTeamInput = new javax.swing.JTextField();
        continueButtonTwo = new javax.swing.JButton();
        errorMessageLabelTwo = new javax.swing.JLabel();
        userInfoConfirmPanel = new javax.swing.JPanel();
        userInfoConfirmLabel = new javax.swing.JLabel();
        userLabelTwo = new javax.swing.JLabel();
        passLabelTwo = new javax.swing.JLabel();
        emailLabelTwo = new javax.swing.JLabel();
        firstLabelTwo = new javax.swing.JLabel();
        lastLabelTwo = new javax.swing.JLabel();
        dobLabelTwo = new javax.swing.JLabel();
        favHistLabelTwo = new javax.swing.JLabel();
        favMovieLabelTwo = new javax.swing.JLabel();
        favTeamLabelTwo = new javax.swing.JLabel();
        newUserUsername = new javax.swing.JLabel();
        newUserPassword = new javax.swing.JLabel();
        newUserEmail = new javax.swing.JLabel();
        newUserFirstName = new javax.swing.JLabel();
        newUserLastName = new javax.swing.JLabel();
        newUserDOB = new javax.swing.JLabel();
        newUserFavHistPerson = new javax.swing.JLabel();
        newUserFavMovie = new javax.swing.JLabel();
        newUserFavTeam = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        newUserAddedPanel = new javax.swing.JPanel();
        newUserAddedLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        newUserDetailsLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        newUserDetailsLabel.setForeground(new java.awt.Color(51, 55, 69));
        newUserDetailsLabel.setText("New User Details");

        userLabelOne.setText("Username: ");

        passLabelOne.setText("Password: ");

        retypePassLabel.setText("Retype Password: ");

        emailLabelOne.setText("Email: ");

        lastLabelOne.setText("Last Name: ");

        firstLabelOne.setText("First Name: ");

        dobLabelOne.setText("Date of Birth: ");

        passInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInputActionPerformed(evt);
            }
        });

        continueButtonOne.setText("Continue");
        continueButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonOneActionPerformed(evt);
            }
        });

        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabel.setText("Error Message!");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserDetailsPanelLayout = new javax.swing.GroupLayout(newUserDetailsPanel);
        newUserDetailsPanel.setLayout(newUserDetailsPanelLayout);
        newUserDetailsPanelLayout.setHorizontalGroup(
            newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(newUserDetailsPanelLayout.createSequentialGroup()
                        .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(continueButtonOne))
                    .addComponent(newUserDetailsLabel)
                    .addGroup(newUserDetailsPanelLayout.createSequentialGroup()
                        .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabelOne)
                            .addComponent(passLabelOne)
                            .addComponent(retypePassLabel)
                            .addComponent(emailLabelOne)
                            .addComponent(firstLabelOne)
                            .addComponent(dobLabelOne)
                            .addComponent(lastLabelOne))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userInput)
                            .addComponent(passInput)
                            .addComponent(retypePassInput)
                            .addComponent(emailInput)
                            .addComponent(firstInput)
                            .addComponent(lastInput)
                            .addComponent(dobInput, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(newUserDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newUserDetailsPanelLayout.setVerticalGroup(
            newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newUserDetailsLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabelOne)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabelOne)
                    .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePassLabel)
                    .addComponent(retypePassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelOne)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabelOne)
                    .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastLabelOne)
                    .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabelOne)
                    .addComponent(dobInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newUserDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueButtonOne)
                    .addComponent(errorMessageLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(newUserDetailsPanel, "card2");

        newUserQuestionsLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        newUserQuestionsLabel.setForeground(new java.awt.Color(51, 55, 69));
        newUserQuestionsLabel.setText("Recovery Questions");

        favHistLabelOne.setText("1. Favorite Historical Figure: ");

        favMovieLabelOne.setText("2. Favorite Movie: ");

        favTeamLabelOne.setText("3. Favorite Sports Team: ");

        favHistInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favHistInputActionPerformed(evt);
            }
        });

        continueButtonTwo.setText("Continue");
        continueButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonTwoActionPerformed(evt);
            }
        });

        errorMessageLabelTwo.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabelTwo.setText("Error Message!");

        javax.swing.GroupLayout newUserQuestionsPanelLayout = new javax.swing.GroupLayout(newUserQuestionsPanel);
        newUserQuestionsPanel.setLayout(newUserQuestionsPanelLayout);
        newUserQuestionsPanelLayout.setHorizontalGroup(
            newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserQuestionsPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(newUserQuestionsPanelLayout.createSequentialGroup()
                        .addComponent(errorMessageLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(continueButtonTwo))
                    .addComponent(newUserQuestionsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserQuestionsPanelLayout.createSequentialGroup()
                        .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(favHistLabelOne)
                            .addComponent(favMovieLabelOne)
                            .addComponent(favTeamLabelOne))
                        .addGap(18, 18, 18)
                        .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(favTeamInput)
                            .addComponent(favHistInput)
                            .addComponent(favMovieInput))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        newUserQuestionsPanelLayout.setVerticalGroup(
            newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserQuestionsPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(newUserQuestionsLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favHistLabelOne)
                    .addComponent(favHistInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favMovieLabelOne)
                    .addComponent(favMovieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favTeamLabelOne)
                    .addComponent(favTeamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newUserQuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueButtonTwo)
                    .addComponent(errorMessageLabelTwo))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(newUserQuestionsPanel, "card3");

        userInfoConfirmLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        userInfoConfirmLabel.setForeground(new java.awt.Color(51, 55, 69));
        userInfoConfirmLabel.setText("Confirm Information");

        userLabelTwo.setText("Username: ");

        passLabelTwo.setText("Password: ");

        emailLabelTwo.setText("Email: ");

        firstLabelTwo.setText("First Name: ");

        lastLabelTwo.setText("Last Name: ");

        dobLabelTwo.setText("Date of Birth: ");

        favHistLabelTwo.setText("Favorite Historical Figure: ");

        favMovieLabelTwo.setText("Favorite Movie: ");

        favTeamLabelTwo.setText("Favorite Sports Team: ");

        newUserUsername.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserUsername.setText("username");

        newUserPassword.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserPassword.setText("password");

        newUserEmail.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserEmail.setText("email");

        newUserFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserFirstName.setText("first name");

        newUserLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserLastName.setText("last name");

        newUserDOB.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserDOB.setText("mm/dd/yyyy");

        newUserFavHistPerson.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserFavHistPerson.setText("person");

        newUserFavMovie.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserFavMovie.setText("movie");

        newUserFavTeam.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newUserFavTeam.setText("team");

        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(100, 30));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.setPreferredSize(new java.awt.Dimension(100, 30));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userInfoConfirmPanelLayout = new javax.swing.GroupLayout(userInfoConfirmPanel);
        userInfoConfirmPanel.setLayout(userInfoConfirmPanelLayout);
        userInfoConfirmPanelLayout.setHorizontalGroup(
            userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userInfoConfirmLabel)
                    .addGroup(userInfoConfirmPanelLayout.createSequentialGroup()
                        .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passLabelTwo)
                            .addComponent(userLabelTwo)
                            .addComponent(emailLabelTwo)
                            .addComponent(firstLabelTwo)
                            .addComponent(lastLabelTwo)
                            .addComponent(dobLabelTwo)
                            .addComponent(favHistLabelTwo)
                            .addComponent(favMovieLabelTwo)
                            .addComponent(favTeamLabelTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserFavHistPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserFavMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUserFavTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userInfoConfirmPanelLayout.createSequentialGroup()
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        userInfoConfirmPanelLayout.setVerticalGroup(
            userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(userInfoConfirmLabel)
                .addGap(18, 18, 18)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabelTwo)
                    .addComponent(newUserUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabelTwo)
                    .addComponent(newUserPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelTwo)
                    .addComponent(newUserEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabelTwo)
                    .addComponent(newUserFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastLabelTwo)
                    .addComponent(newUserLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabelTwo)
                    .addComponent(newUserDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favHistLabelTwo)
                    .addComponent(newUserFavHistPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favMovieLabelTwo)
                    .addComponent(newUserFavMovie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favTeamLabelTwo)
                    .addComponent(newUserFavTeam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userInfoConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(userInfoConfirmPanel, "card4");

        newUserAddedLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        newUserAddedLabel.setForeground(new java.awt.Color(51, 55, 69));
        newUserAddedLabel.setText("User Added Successfully!");

        okButton.setText("OK");
        okButton.setPreferredSize(new java.awt.Dimension(100, 30));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserAddedPanelLayout = new javax.swing.GroupLayout(newUserAddedPanel);
        newUserAddedPanel.setLayout(newUserAddedPanelLayout);
        newUserAddedPanelLayout.setHorizontalGroup(
            newUserAddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserAddedPanelLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(newUserAddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUserAddedLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserAddedPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        newUserAddedPanelLayout.setVerticalGroup(
            newUserAddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserAddedPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(newUserAddedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        getContentPane().add(newUserAddedPanel, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void favHistInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favHistInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favHistInputActionPerformed

    private void passInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passInputActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        userInfoConfirmPanel.setVisible(false);
        newUserDetailsPanel.setVisible(true);
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void continueButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonOneActionPerformed
        // TODO add your handling code here:
        if(userInput.getText().equals("")){
            errorMessageLabel.setText("You need to enter a Username!");
            errorMessageLabel.setVisible(true);
        }
        else if(passInput.getText().equals("")){
            errorMessageLabel.setText("You need to enter a Password!");
            errorMessageLabel.setVisible(true);
        }
        else if(emailInput.getText().equals("")){
            errorMessageLabel.setText("You need to enter an Email!");
            errorMessageLabel.setVisible(true);
        }
        else{
            if(passInput.getText().equals(retypePassInput.getText())){
                newUserDetailsPanel.setVisible(false);
                newUserQuestionsPanel.setVisible(true);
                errorMessageLabel.setVisible(false);
            }
            else{
                errorMessageLabel.setText("Passwords do not match!");
                errorMessageLabel.setVisible(true);
            }
        }
    }//GEN-LAST:event_continueButtonOneActionPerformed

    private void continueButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonTwoActionPerformed
        // TODO add your handling code here:
        if(favHistInput.getText().equals("")){
            errorMessageLabelTwo.setText("Enter a Favorite Historical Figure!");
            errorMessageLabelTwo.setVisible(true);
        }
        else if(favMovieInput.getText().equals("")){
            errorMessageLabelTwo.setText("Enter a Favorite Movie!");
            errorMessageLabelTwo.setVisible(true);
        }
        else if(favTeamInput.getText().equals("")){
            errorMessageLabelTwo.setText("Enter a Favorite Sports Team!");
            errorMessageLabelTwo.setVisible(true);
        }
        else{
            newUserUsername.setText(userInput.getText());
            newUserPassword.setText(passInput.getText());
            newUserEmail.setText(emailInput.getText());
            if(firstInput.getText().equals("")){
                newUserFirstName.setText("");
            }
            else{
                newUserFirstName.setText(firstInput.getText());
            }
            if(lastInput.getText().equals("")){
                newUserLastName.setText("");
            }
            else{
                newUserLastName.setText(lastInput.getText());
            }
            if(dobInput.getText().equals("")){
                newUserDOB.setText("");
            }
            else{
                newUserDOB.setText(dobInput.getText());
            }
            newUserLastName.setText(lastInput.getText());
            newUserDOB.setText(dobInput.getText());
            newUserFavHistPerson.setText(favHistInput.getText());
            newUserFavMovie.setText(favMovieInput.getText());
            newUserFavTeam.setText(favTeamInput.getText());
            newUserQuestionsPanel.setVisible(false);
            userInfoConfirmPanel.setVisible(true);
            errorMessageLabelTwo.setVisible(false);
        }
    }//GEN-LAST:event_continueButtonTwoActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        userInfoConfirmPanel.setVisible(false);
        newUserAddedPanel.setVisible(true);
        User newUser = new User(userInput.getText(),passInput.getText(),firstInput.getText(),lastInput.getText(),emailInput.getText(),dobInput.getText(),favHistInput.getText(),favMovieInput.getText(),favTeamInput.getText());
        UserList.userRecover.put(emailInput.getText(),userInput.getText());
        UserList.users.put(userInput.getText(), newUser);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_okButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactEditorUI tmp = new ContactEditorUI();
        tmp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton continueButtonOne;
    private javax.swing.JButton continueButtonTwo;
    private javax.swing.JTextField dobInput;
    private javax.swing.JLabel dobLabelOne;
    private javax.swing.JLabel dobLabelTwo;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabelOne;
    private javax.swing.JLabel emailLabelTwo;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel errorMessageLabelTwo;
    private javax.swing.JTextField favHistInput;
    private javax.swing.JLabel favHistLabelOne;
    private javax.swing.JLabel favHistLabelTwo;
    private javax.swing.JTextField favMovieInput;
    private javax.swing.JLabel favMovieLabelOne;
    private javax.swing.JLabel favMovieLabelTwo;
    private javax.swing.JTextField favTeamInput;
    private javax.swing.JLabel favTeamLabelOne;
    private javax.swing.JLabel favTeamLabelTwo;
    private javax.swing.JTextField firstInput;
    private javax.swing.JLabel firstLabelOne;
    private javax.swing.JLabel firstLabelTwo;
    private javax.swing.JTextField lastInput;
    private javax.swing.JLabel lastLabelOne;
    private javax.swing.JLabel lastLabelTwo;
    private javax.swing.JLabel newUserAddedLabel;
    private javax.swing.JPanel newUserAddedPanel;
    private javax.swing.JLabel newUserDOB;
    private javax.swing.JLabel newUserDetailsLabel;
    private javax.swing.JPanel newUserDetailsPanel;
    private javax.swing.JLabel newUserEmail;
    private javax.swing.JLabel newUserFavHistPerson;
    private javax.swing.JLabel newUserFavMovie;
    private javax.swing.JLabel newUserFavTeam;
    private javax.swing.JLabel newUserFirstName;
    private javax.swing.JLabel newUserLastName;
    private javax.swing.JLabel newUserPassword;
    private javax.swing.JLabel newUserQuestionsLabel;
    private javax.swing.JPanel newUserQuestionsPanel;
    private javax.swing.JLabel newUserUsername;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField passInput;
    private javax.swing.JLabel passLabelOne;
    private javax.swing.JLabel passLabelTwo;
    private javax.swing.JTextField retypePassInput;
    private javax.swing.JLabel retypePassLabel;
    private javax.swing.JLabel userInfoConfirmLabel;
    private javax.swing.JPanel userInfoConfirmPanel;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userLabelOne;
    private javax.swing.JLabel userLabelTwo;
    // End of variables declaration//GEN-END:variables
}
